# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end

#add the Firebase pod for Google Analytic
pod 'Firebase/Analytics'
# or pod 'Firebase/AnalyticWithoutAdIdSupport'
# for Analytic without IDFA collection capability
# add pods for any other desired Firebase projects
# https://firebase.google.com/docs/ios/setup#available-pods
